SELECT E.EMPLOYEE_ID
FROM EMPLOYEES AS E
LEFT JOIN SALARIES AS S
    ON E.EMPLOYEE_ID = S.EMPLOYEE_ID
WHERE S.SALARY IS NULL

UNION

SELECT S.EMPLOYEE_ID
FROM SALARIES AS S
LEFT JOIN EMPLOYEES AS E
    ON S.EMPLOYEE_ID = E.EMPLOYEE_ID
WHERE E.NAME IS NULL

ORDER BY EMPLOYEE_ID ASC;